### ISSUE TITLE
Messages not always received by RabbitMq server

### ISSUE THREAD

**Issue by Aorimn** [sozu-proxy/lapin#142]
Hi,
I tried the publish example of the [documentation](https://docs.rs/lapin-futures/0.14.0/lapin_futures/index.html) and modified it so that it publishes 10K messages. The resulting code is [available here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=f06174b4ab836a9a3e4ad7c8d94c7f55) (there's also an exchange declared and binding the hello queue to this exchange, but that's not really the subject).

When compiling this snippet in debug, all goes well: I get all of the 10K messages in the hello queue (seeing it using the management plugin). However, when compiled as release, the number of messages in the queue is inconsistent from a run to the other.

I found out that adding `.and_then(move |_| channel.close(0, "OK"))` after the call to `join_all` will enable the messages to be correctly sent, as was in the debug build.

So, multiple points here:
- I don't think the user of the library should manually close the channel. I would think the Drop trait a good idea in classic rust programming, but I don't know if it plays well with futures. If the user of the library must manually ensure the closing of a channel, it would be a good idea to have this line added in the documentation.
- Is there a list of codes and messages that is available with the description about what those code/message do?

**Comment by Keruspe** [comment]
Wrt the code/message part, there is no standard to my knowledge. You can basically put anything you want. It might just help you find the logs more easily.

I'll make some tests to see why the queue isn't flushed correctly if you don't close manually

**Comment by Aorimn** [comment]
Thanks for the code/message, I thought that was an AMQP or lapin standard but if it's anything, then anything will do.

**Comment by Keruspe** [comment]
Does this problem still exist?

**Comment by Keruspe** [comment]
If you’re using a confirm channel, the problem might be related to the message that haven’t been acked by the server yet when the channel gets closed.

Wrt channel close codes, when there is no error it should be 200 (or

**Comment by Aorimn** [comment]
I believe the issue to still exist.

[The code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3c765493c936c1d011a40de0a59aba23) with the latest (0.18) lapin-futures crate and the related [Cargo.toml](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=281137d1bf28e6a8cb3cb9f135c15abd).

In the aforementioned code, I've put the new related `channel.close` call in comment: with it, all the 10K messages are there, without only a handful of them are put in the queue.

**Comment by Keruspe** [comment]
Thanks for taking the time to confirm that, will give it a look once I’m
done with some big refactoring

**Comment by Keruspe** [comment]
Care to try with 0.19.0 beta1?

**Comment by Aorimn** [comment]
Sure, here are the test results for [this code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2e896e317dacd80c06bae51899574b30) using [this Cargo.toml](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8bdc11ac845496813e27950f7daf022b) (beta2 I believe).

| Debug without channel.close() | Debug with channel.close() | Release without channel.close() | Release with channel.close() |
|-------------------------------|----------------------------|---------------------------------|------------------------------|
| 9978                          | 10000                      | 9976                            | 10000                        |

So one good thing is that now debug vs release looks consistent.

To be completely transparent, when I add the `channel.close()` that is commented in [the code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2e896e317dacd80c06bae51899574b30), line 110, the program never finishes, whether it's in debug or release. I think this could impact the tests, so do you have an idea of what do I miss?

**Comment by Aorimn** [comment]
On an somewhat unrelated note, do I have another option as to use `lapin_asnc` in `lapin_async::credentials::Credentials` with the current state? I've not seen it re-exported in `lapinfutures`.

**Comment by Keruspe** [comment]
There are a couple of reexports missing from lapin_futures atm yep, I haven't really focused on that yet

**Comment by Keruspe** [comment]
The hang when doing channel_close is fixed by 283fb1f92572199a893e1692d2bb7a5a34a4d00a

**Comment by Keruspe** [comment]
Now wrt this issue, it's not an actual issue in lapin but rather in how AMQP works I think.

Let me explain:

When you do a channel_close, we expect a channel_close-ok from the server, so we wait for it before terminating the future, thus ensuring the server got our message and replied to us. As the basic_publish calls have been done before that, this also ensures that those were correctly handled by the server too.

When you do not call channel_close, the future ends when the message has been written on the socket (so the server hasn't received it yet). Depending on the latency, speed, etc, all messages can be received before we close the socket when the program exits, or some might have been written but not yet read when the socket was closed. (Note that prior to 0.19, the future was terminated when queuing the message for send, and now when it has actually been sent, that's why the results are more consistant now).

If you want to ensure the messages have been well received, AMQP has something to tell the server to ack messages once received: publisher_confirms. If you call confirm_select on the channel after creating it, and you call channel.wait_for_confirms(), the client will wait until the server has successfully ack'ed the last sent message (which isn't guaranteed to be immediate by the AMQP specs). This will, as a bonus, return you a Vec of the messages that couldn't be properly handled by the server because of lack of resources or such

**Comment by Keruspe** [comment]
beta3 should have the fix for the hang

**Comment by Aorimn** [comment]
I've come across this publish_confirms just recently and didn't make the connection, but that would indeed explain what we see.

I'll have a go at beta3 tomorrow morning and let you know. Thanks for all the work you're doing on this!

**Comment by Aorimn** [comment]
Tested with 0.19.0-rc1, the hang doesn't happen anymore. Also, exports look better 👍 

I suppose this issue can be closed then, as per [your explanation](https://github.com/sozu-proxy/lapin/issues/142#issuecomment-500215636) regarding publish_confirms. Thanks again and keep up the good work!
