### ISSUE TITLE
Endless wait for a basic_ack

### ISSUE THREAD

**Issue by tyrylu** [sozu-proxy/lapin#204]
Hello,
any idea why a wait after a basic_ack in lapin 0.26.9 would block indefinitely? The same channel as for the consumer creation is used and nothing else happens on this channel, yes, a second channel exists but that's only for some basic_publish calls which work fine.
All the threads except for the application thread are stuck in a mio poll...

**Comment by Keruspe** [comment]
Hello,
I'll give this a look. Do you always reproduce the problem or does it only happens sometimes?
Do you have a minimal reproducer available?

**Comment by tyrylu** [comment]
I am afraid that it happens somewhat anytime. The relevant code is here: https://github.com/tyrylu/feel-the-streets/blob/master/server/src/bin/worker.rs
Some of the tasks can create a second connection, but that does not change the outcome.

**Comment by Keruspe** [comment]
How can I easily reproduce the problem?

**Comment by tyrylu** [comment]
The behavior is even weirder with the 0.27 beta 5 version. Calling channel.basic_ack(...).into_error() (as in the example) results in a return, however the trace logs indicate that no ack frame is being send:
```
[INFO  worker] Task executed successfully.
[TRACE lapin::connection] connection send_frame; channel_id=1
[TRACE lapin::connection] connection set readable
[INFO  worker] Task acknowledged.
[TRACE lapin::connection] connection send_frames; channel_id=2
[TRACE lapin::connection] connection set readable
[TRACE lapin::io_loop] io_loop send continue; can_read=true, can_write=true, has_data=false
[TRACE lapin::io_loop] io_loop do_run done; can_read=true, can_write=true, has_data=false, status=Setup
[TRACE lapin::io_loop] io_loop run
[TRACE lapin::io_loop] io_loop poll
[TRACE lapin::io_loop] io_loop poll done
[TRACE lapin::io_loop] io_loop do_run; can_read=true, can_write=true, has_data=false
[TRACE lapin::io_loop] io_loop do_run done; can_read=false, can_write=true, has_data=false, status=Setup
[TRACE lapin::io_loop] io_loop run
[TRACE lapin::io_loop] io_loop poll

```
As if the io loop didn't notice the request to send the data or something.

**Comment by Keruspe** [comment]
Ok, I got what's going on:
Currently, the thread running the consumers is the same as the one doing the I/O. Waiting for the result of basic_ack hence blocks it, preventing it from actually sending the basic_ack.
This is stupid, I really have to change that.
Wrt the into_error stuff, I'll just remove it, it's misleading, it basically tells you if there was an error when scheduling the message to be sent, it doesn't actually wait for it to be sent.
I'll try to find an easy fix until the various io_loop issues are fixed. in the meantime, i suggest you to use a crossbeam channel, spawn a thread (or more), waiting for new messages, and in your consumer, juste post the message in the crossbeam channel. (This is the pattern I use everywhere, that's why I never hit this bug myself)

**Comment by tyrylu** [comment]
Thank you, i'll look into it, i thought that i will simplify the worker (previously there were threads mainly because of some tokio runtime related issues), so it seems they'll return at least for a while.

**Comment by Keruspe** [comment]
Can you retry with 0.27.0-beta.6?

**Comment by tyrylu** [comment]
I'll try and report sometime tomorrow in the morning after the scheduled task executes.

**Comment by tyrylu** [comment]
Thank you, beta 6 works as expected.

**Comment by Keruspe** [comment]
Thanks for confirming!
