### ISSUE TITLE
Channel not closed on drop

### ISSUE THREAD

**Issue by fan-tom** [sozu-proxy/lapin#211]
When Channel object is dropped, channel is not closed on rabbit. Is it desired behavior or we need to somehow register channel id to close on drop  and on later iteration of io-loop send corresponding command to rabbit to not leak resources?

**Comment by Keruspe** [comment]
Hi,

For now is is the expected behaviour, as closing a channel in rabbitmq requires a "reason".
I could try to make things happen with some default reason

**Comment by Keruspe** [comment]
After thinking more about this, I don't think we'll do this in lapin.
It should be easy enough to make a struct, wrap the channel inside, impl Deref to be able to access the channel methods directly on the struct and close the inner channel when the struct is dropped, but I think you should do that in your application rather than in lapin (given channels can be cloned and shared between threads in lapin)

**Comment by Keruspe** [comment]
A copy of channels are stored in the connection, amongst other things, so there always is a reference in lapin internals until explicitely closed.
The choice here is to have something flexible for all needs in the lapin library. There are lots of ways you can use them at the application level afterwards, which depends mostly on your software architecture or coding style.
Wrapping the channel in some kind of Arc<CustomChannel> sounds like a good match for what you're describing

**Comment by Keruspe** [comment]
@fan-tom I just added this CloseOnDrop thing that will probably do just what you want

**Comment by fan-tom** [comment]
Great, thank you. Maybe it is better to use this wrapper by default to not confuse newcomers with leaking resources, and describe that if they want clonable channel, they must `into_inner` it and close them manually or wrap into some sort of Rc?

**Comment by Keruspe** [comment]
Opened #250
