### ISSUE TITLE
Orthodox API for protocol methods

### ISSUE THREAD

**Issue by michaelklishin** [sozu-proxy/lapin#23]
I know very little about Rust but this client uses a very uncommon (for OO-ish languages) API for channel operations (say, `queue.declare`).

In Java, C#, Ruby (Bunny), Python (Pika) `queueDeclare` and similar are methods on a channel. In Erlang, Clojure (Langohr), Haskell they are functions that accept a channel as the first parameter and are unaware of the connection.

According to [this example](https://github.com/Geal/lapin/blob/master/async/examples/connection.rs#L52), in Lapin `queue_declare` is a connection method that accepts a channel. What's the idea behind
this decision? Even if the idea is to introduce a special lower-level API, most protocol operations
are channel-scoped (not counting `connection.start` or `channel.open`, of course).

It is not unheard of for applications that use the aforementioned clients to accept channels and be very much unaware of what connection said channel is on.

**Comment by michaelklishin** [comment]
I now see the [futures API](https://github.com/Geal/lapin/blob/master/futures/examples/client.rs#L30) moves protocol operations to methods on channels.

I'd still recommend sticking to the same strategy other clients use unless there are Rust-specific reasons to not do that. Your client's API will be easier to pick up to anyone who's used a decently popular RabbitMQ library in another language before ;)

**Comment by Geal** [comment]
"Connection" is a bad name for it, I should rename it to "protocol" or "state machine". Having that one object managing everything simplifies the design a lot. The async library is meant as a low level library on which an API can be built, not a user friendly client that can be picked up and work out of the box. Passing the channel as first argument could be useful though, I'll look into it.

Are there things we should change in the futures API? There are two things I'd like feedback on:

- the `create_channel` and `create_confirm_channel` method make a `Channel` for which `basic_publish` will return `None` if the confirm extension has not been activated, `Some(true)` if the message was accepted, `Some(false)` if it was rejected. I feel I should make separate `Channel` and `ConfirmChannel` elements with the same API, except `Channel` would have the transaction methods, and `ConfirmChannel` would have a `basic_publish` that returns a future resolving with the confirmation result
- I want to add a version of `basic_get` or `basic_consume` that return a `Message` on which there's the `ack` method, to allow acknowledging the message from anywhere in the code, instead of the part of the code that holds a `Channel` instance. It would be a bit heavier than getting the delivery tag from the message and passing to the channel's ack method, as every message would hold a refcounted instance of the underlying transport

do you think those approaches would be interesting?

**Comment by michaelklishin** [comment]
I think that if publisher confirms are not enabled it would make more sense to return a `Some(true)` (an optional, rather than `None`). Otherwise your first point makes sense to me.

As for the second one, Bunny has something similar. The problem there is that acks (or nacks) must be sent on the same channel they were received on. This is complicated by connection recovery, see the versioned delivery tag feature in Bunny, Java, C# (IIRC) clients. Otherwise this design is OK.

Since Rust has the idea of message passing (IIRC), another approach to acks is to return a stream of acks. This makes more sense for publishers than consumers. That's how the Go client exposes publisher confirms. Just an idea.

**Comment by ijsgaus** [comment]
I mean, consume basic_consume api in this featured version can recieve: `FnOnce<Message> -> Feature<Confirm, _>` , where 
`Confirm -> enum { Ack, Nack, Requeue }`

**Comment by Keruspe** [comment]
Fwiw, I’m working on a rework/refactor that should land by the end of the month which should improve that a lot

**Comment by Keruspe** [comment]
Should be fixed in Can you try with 0.19.0-alpha1?
