### ISSUE TITLE
Mutable self in consumer delegate?

### ISSUE THREAD

**Issue by arnauorriols** [sozu-proxy/lapin#234]
I have an `FnMut` that I want to use to consume the messages using the `ConsumerDelegate` trait. However, the `ConsumerDelegate` uses an immutable reference to self, which means I cannot borrow self (or any of its contents AFAIK) as mutable, and so I cannot execute the `FnMut` which is inside self:
```rust
pub struct ConsumerFn<F: FnMut(Msg) + Sync + Send> {
	pub consumer_fn: F
}

impl<F: FnMut(Msg) + Sync + Send> lapin::ConsumerDelegate for ConsumerFn<F> {
	fn on_new_delivery(&self, delivery: lapin::message::DeliveryResult) {
		(self.consumer_fn)(
			delivery
				.expect("Consumer failure")
				.expect("Consumer cancelled")
				.into(),
		)
	}
}
```
```
error[E0596]: cannot borrow `self.consumer_fn` as mutable, as it is behind a `&` reference
  --> src/domain.rs:39:3
   |
38 |     fn on_new_delivery(&self, delivery: lapin::message::DeliveryResult) {
   |                        ----- help: consider changing this to be a mutable reference: `&mut self`
39 |         (self.consumer_fn)(
   |         ^^^^^^^^^^^^^^^^^^ `self` is a `&` reference, so the data it refers to cannot be borrowed as mutable

error: aborting due to previous error

For more information about this error, try `rustc --explain E0596`.
```

Is this achievable somehow? Apologies in advance if the question is wrong, I'm still quite new with Rust!

**Comment by Keruspe** [comment]
Hi,

Do you really need a FnMut or is a Fn enough? Is a Fn is enough, then you can just use the fn itself instead of your struct like `consumer.set_delegate(Box::new(my_fn))`

Note that when using the delegate feature, we spawn the delegate with the delivery on a thread pool as soon as we receive a message. While the default pool size is one, it can be more than one, so you won't have your mutable object shared between all those threads. Actually, we even clone the delegate before spawning it on the thread pool.

You can use `Arc<Foo>` to share the same instance across these, and `Arc<Mutex<Foo>>` if you need mutable access, as calling `lock()` on the mutex will give you a mutable reference

**Comment by arnauorriols** [comment]
> Do you really need a FnMut or is a Fn enough?

Yes, I need an FnMut because it's supposed to be a closure where state is stored between messages. I could use an struct but the mutable ref would still be necessary. 

> You can use Arc<Foo> to share the same instance across these, and Arc<Mutex<Foo>> if you need mutable access, as calling lock() on the mutex will give you a mutable reference

Cool, Thanks for the tip!
