### ISSUE TITLE
Customizing rustls ClientConfig

### ISSUE THREAD

**Issue by jothan** [sozu-proxy/lapin#242]
Hi,

Currently, lapin does not seem to expose a way to create a custom connection. The deprecated lapin-futures crate seems to expose a Client struct that would do, but a good portion is marked deprecated.

I am connecting to a RabbitMQ instance with a certificate that is not in the main certificate store and I do not wish to trust the usual certificate authorities or modify the global store.

I am using the latest tokio 0.2.

Please advise,
Jonathan

**Comment by Keruspe** [comment]
Hi,

In fact the whole lapin-futures crate is deprecated (and in fact, it was dropped in 0.34.0).

Here is an example of customizing the underlying tls engine: https://github.com/sozu-proxy/lapin/blob/master/examples/custom_tls_connection.rs

This example is using native-tls, but it's basically the same for rustls, apart from using `into_rustls` instead of `into_native_tls`.

**Comment by jothan** [comment]
Ok, looks more like a documentation issue, I can't find the connect method accepting a closure with the stream using docs.rs.

https://docs.rs/lapin/0.34.0/lapin/index.html?search=connect

**Comment by Keruspe** [comment]
It’s not inside lapin, but inside amq_protocol::tcp

**Comment by Keruspe** [comment]
You’re right though, this definitely should be better documented (what’s in lapin/amq-protocol/tcp-stream)

If you have ideas wrt this, it would be greatly appreciated

**Comment by jothan** [comment]
I would probably have found it on my own eventually, moving the example into the docs somewhere might help.

Merci Marc-Antoine !
