### ISSUE TITLE
Dropping Connection leaks the connection

### ISSUE THREAD

**Issue by jothan** [sozu-proxy/lapin#247]
I am in the process of connecting our app to RabbitMQ and I have started testing the latest lapin 0.35.2 code.

I am using a custom Rustls connection with code very similar to the example.

With the following code, the connection succeeds and is dropped immediately. However, the connection stays up and heartbeats are periodically exchanged. The RabbitMQ web interface confirms that the connection is still up.

Does Connection absolutely require a close() call ?

```rust
 let conn = custom_connect(uri, Default::default(), client_config).await.unwrap();
drop(conn);
// Rest of application
```

**Comment by Keruspe** [comment]
Connection absolutely requires a close() call.
First, the close() call takes arguments (which you then find in the server's logs for example), and then the Connection implements Clone, and some parts of lapin's internals own a copy to that (the io loop, amongst others), rendering it difficult to track whether only lapin still owns references to the connection or not.
Note that the same applies to channel, and there was already an issue for that #211 

My advice: if you want to automatically close the connection, wrap it in your own struct and call close in the Drop of this one.

I might add some `CloseOnDrop<T>` wrapper at some point (so that you can have a `CloseOnDrop<Connection>` and a `CloseOnDrop<Channel>`) but never got around to actually implement this. Still not sure that's something we want to do

**Comment by jothan** [comment]
Ok, I'll submit a PR with a documentation update in that case.

Thanks !

**Comment by Keruspe** [comment]
Thanks a lot for the reports of these last few days, really appreciated!

Documentation is really... minimal at this point, there's definitely room for loads of improvements and clarifications.

**Comment by jothan** [comment]
Having Weak references in there and avoiding all cycles would be nice, but I see how it would complicate stuff in the IO loop. Still, having a completely floating connection seems wrong.

CloseOnDrop wrappers should be just as reliable, updating the docs will prevent any further suprises for others.

**Comment by Keruspe** [comment]
I think we can close this, now that CloseOnDrop is there
