### ISSUE TITLE
What's the benefit of the `CloseOnDrop` newtype?

### ISSUE THREAD

**Issue by arnauorriols** [sozu-proxy/lapin#263]
First of all, apologies in advanced, my journey with rust is still young, and I might be missing some knowledge.

I'm currently upgrading from 0.32 to 0.39, and I'm facing the addition of `CloseOnDrop`. I'm wondering what value it adds, considering the drawback in ergonomic of the public API. Why not just implement Drop for `Connection` and `Channel`?

**Comment by Keruspe** [comment]
Which drawback are you speaking of?

Calling .into_inner() will restore the previous behaviour while keeping the CloseOnDrop will automatically close the channel or connection when dropped. It’s an easy way of making that optional, with an easy way to opt out of it, and since it implements Deref it’s basically transparent.

Which issue are you facing?

**Comment by Keruspe** [comment]
Also, Connection and Channel are used internally by lapin and are clonable, so it felt safer to split this

**Comment by arnauorriols** [comment]
Not a big issue, just a bit more cumbersome API. I was just curious. Thanks for answering!

**Comment by jbg** [comment]
What is the use case in the public API for a Connection or Channel that does _not_ close on drop? In the very unlikely case a user of this library wants to leak a connection or channel (i.e. drop it without closing the connection/channel), they could do that with `mem::forget` anyway. This seems like extra API noise, and worse ergonomics when needing to name the types to store a Connection/Channel, without any tangible benefit.

**Comment by Keruspe** [comment]
In my personal use case, I never use the automatic close on drop. I really don't see what's the problem here, tbh, am I really missing some crucial ergonomic point?
Having the connection and the channels close on drop doesn't guarantee that the channels will be closed before the connection, for example. It's not a really big deal, but it produces noise for noting.
I might want to create one channel, then no to be bothered with the connection anymore and only carry my channel around, why would it be closed as soon as I don't use the connection anymore?

**Comment by jbg** [comment]
The general pattern in every similar Rust library is that objects own their resources, and the resources are dropped when the object is dropped. Any different behaviour is surprising, and makes the library less ergonomic. Like OP, I took a double-take the first time I saw `CloseOnDrop`. As well as being unidiomatic Rust, it also makes use of the library more prone to pitfalls like memory/fd leaks. This is somewhat ameliorated by the fact that you have to do extra work to unwrap the type from the `CloseOnDrop`, but the methods that do that unwrapping are not marked `unsafe` despite returning resources that will leak unless the programmer remembers to clean them up.

Keeping the `Connection` open as long as any `Channel` is using it would typically be solved by having the `Channel`s share ownership of the `Connection`, for example with an `Rc`/`Arc`, so that the `Connection` was not dropped until the last `Channel` created from it was. This is a pretty common pattern in similar Rust libraries. If there are other types that need to keep a Channel open, you could follow a similar pattern for those.

**Comment by Keruspe** [comment]
The problem being that the Connection already owns the Channels, as it needs to use a channel for e.g. .... closing itself. So you end up with a cicle and never release anything.

There definitely is room for improvement here, and I'm still trying stuff in this area and am totally open to things here (#276 being one step closer to dropping this behaviour shows that I'm wiling to do that, I think).

There has been lots of discussion lately around "leaks" and memory management, especially around rio and such, and afaik the consensus was that it's easy to "leak" data in safe rust thanks to mem::forget or ManuallyDrop for example, which tends to confirm that into_inner shouldn't be unsafe imo, but I'd be happy to make it unsafe if it makes things clearer wrt the current state of this

**Comment by Keruspe** [comment]
After some more tinking and tinkering, CloseOnDrop is now gone.
Channels are closed when dropped, unless it has already been closed.
Connection is closed when dropped and when all the Channels have been dropped, unless it has already been closed.
