### ISSUE TITLE
Expose Message in lapin_futures

### ISSUE THREAD

**Issue by cptaffe** [sozu-proxy/lapin#89]
The function [`basic_get`](https://docs.rs/lapin-futures/0.10.0/lapin_futures/channel/struct.Channel.html#method.basic_get) returns a `Box<Future<Item=Message...>>` but the type [`Message`](https://docs.rs/lapin-async/0.10.0/lapin_async/queue/struct.Message.html) isn't exposed in `lapin_futures`. I don't really want to depend on `lapin_async` myself just to be able to write type signatures for processing messages.

**Comment by ChristophWurst** [comment]
In case anybody finds this ticket because they updated to the latest version of `lapin_futures` and wondered why `Message` disappeared: it has been renamed in https://github.com/sozu-proxy/lapin/commit/c896843267ddfc9f7be165d17797d92e7d621f65.

Ref https://github.com/schani-rs/schani_processor/pull/26/commits/84af2aa9d2d71d8c8d4b88770263e08267597e6f
